
import { 
  Brain, 
  Heart, 
  MessageCircle, 
  BarChart3, 
  User, 
  Calendar, 
  Settings, 
  Target, 
  TrendingUp, 
  Users, 
  Building, 
  BookOpen, 
  Book, 
  FileText,
  Phone,
  Video,
  Mic,
  Shield,
  CreditCard,
  Clock,
  Globe,
  Lightbulb,
  Star,
  Award,
  CheckCircle,
  Play,
  Headphones,
  Camera,
  Lock,
  Database,
  Download,
  Activity,
  School,
  Stethoscope,
  GraduationCap,
  Briefcase,
  UserCheck,
  HelpCircle,
  BookOpenCheck,
  MessageSquare,
  Search,
  TrendingDown,
  Calendar as CalendarIcon,
  PhoneCall,
  LucideIcon,
  Zap,
  Compass,
  LayoutDashboard,
  Plug,
  Code,
  Smartphone,
  LifeBuoy,
  Watch
} from 'lucide-react';

// Custom icon imports (these would be replaced with actual custom SVG components)
const customIcons: Record<string, LucideIcon> = {
  'therapy-ai-core': Brain,
  'ai-therapy-chat': MessageCircle,
  'ai-personalization': User,
  'adaptive-systems': Settings,
  'cognitive-behavioral-therapy': Brain,
  'dialectical-behavior-therapy': Heart,
  'mindfulness-based-therapy': Compass,
  'trauma-focused-therapy': Shield,
  'cultural-ai': Globe,
  'voice-ai-therapy': Mic,
};

// Map of icon names to Lucide components
const iconMap: Record<string, LucideIcon> = {
  Brain,
  Heart,
  MessageCircle,
  BarChart3,
  User,
  Calendar,
  Settings,
  Target,
  TrendingUp,
  Users,
  Building,
  BookOpen,
  Book,
  FileText,
  Phone,
  Video,
  Mic,
  Shield,
  CreditCard,
  Clock,
  Globe,
  Lightbulb,
  Star,
  Award,
  CheckCircle,
  Play,
  Headphones,
  Camera,
  Lock,
  Database,
  Download,
  Activity,
  School,
  Stethoscope,
  GraduationCap,
  Briefcase,
  UserCheck,
  HelpCircle,
  BookOpenCheck,
  MessageSquare,
  Search,
  TrendingDown,
  CalendarIcon,
  PhoneCall,
  Zap,
  Compass,
  LayoutDashboard,
  Plug,
  Code,
  Smartphone,
  LifeBuoy,
  Watch,
};

export const getItemIcon = (iconName: string): LucideIcon => {
  return customIcons[iconName] || iconMap[iconName] || Brain; // Check custom icons first, then fallback
};
