-- Update navigation items to use new custom icon names
UPDATE navigation_menu_items SET icon = 'group-therapy-ai' WHERE icon = 'Users' AND title = 'Group Therapy AI';
UPDATE navigation_menu_items SET icon = 'ai-therapist-team' WHERE icon = 'Stethoscope' AND title = 'AI Therapist Team';
UPDATE navigation_menu_items SET icon = 'mood-progress-tracking' WHERE icon = 'TrendingUp' AND title = 'Mood & Progress Tracking';
UPDATE navigation_menu_items SET icon = 'crisis-support-system' WHERE icon = 'Shield' AND title = 'Crisis Support System';
UPDATE navigation_menu_items SET icon = 'family-account-sharing' WHERE icon = 'Users' AND title = 'Family Account Sharing';
UPDATE navigation_menu_items SET icon = 'community-groups' WHERE icon = 'Users' AND title = 'Community & Groups';
UPDATE navigation_menu_items SET icon = 'integrations-hub' WHERE icon = 'Plug' AND title = 'Integrations Hub';
UPDATE navigation_menu_items SET icon = 'crisis-support' WHERE icon = 'LifeBuoy' AND title = 'Crisis Support';
UPDATE navigation_menu_items SET icon = 'api-access' WHERE icon = 'Code' AND title = 'API Access';
UPDATE navigation_menu_items SET icon = 'mobile-apps' WHERE icon = 'Smartphone' AND title = 'Mobile Apps';
UPDATE navigation_menu_items SET icon = 'data-export' WHERE icon = 'Download' AND title = 'Data Export';
UPDATE navigation_menu_items SET icon = 'custom-integrations' WHERE icon = 'Plug' AND title = 'Custom Integrations';
UPDATE navigation_menu_items SET icon = 'wearable-integration' WHERE icon = 'Watch' AND title = 'Wearable Integration';
UPDATE navigation_menu_items SET icon = 'for-individuals' WHERE icon = 'User' AND title = 'For Individuals';
UPDATE navigation_menu_items SET icon = 'for-families' WHERE icon = 'Users' AND title = 'For Families';
UPDATE navigation_menu_items SET icon = 'for-organizations' WHERE icon = 'Building' AND title = 'For Organizations';
UPDATE navigation_menu_items SET icon = 'pricing-plans' WHERE icon = 'CreditCard' AND title = 'Pricing Plans';
UPDATE navigation_menu_items SET icon = 'healthcare-providers' WHERE icon = 'Stethoscope' AND title = 'Healthcare Providers';
UPDATE navigation_menu_items SET icon = 'enterprise-security' WHERE icon = 'Lock' AND title = 'Enterprise Security';
UPDATE navigation_menu_items SET icon = 'how-it-works' WHERE icon = 'Lightbulb' AND title = 'How It Works';
UPDATE navigation_menu_items SET icon = 'support-center' WHERE icon = 'LifeBuoy' AND title = 'Support Center';
UPDATE navigation_menu_items SET icon = 'learning-hub' WHERE icon = 'GraduationCap' AND title = 'Learning Hub';
UPDATE navigation_menu_items SET icon = 'blog-insights' WHERE icon = 'BookOpen' AND title = 'Blog & Insights';
UPDATE navigation_menu_items SET icon = 'research-studies' WHERE icon = 'FileText' AND title = 'Research & Studies';
UPDATE navigation_menu_items SET icon = 'therapist-directory' WHERE icon = 'Users' AND title = 'Therapist Directory';
UPDATE navigation_menu_items SET icon = 'mental-health-library' WHERE icon = 'BookOpenCheck' AND title = 'Mental Health Library';